# Generated by Django 4.2 on 2023-05-31 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0008_user_comments_liked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
